import esbuild from 'esbuild'

await esbuild.build({
  entryPoints: ['src/eslint/index.ts'],
  outfile: 'dist/eslint/index.js',
  bundle: true,
  minify: true,
  format: 'esm',
  platform: 'node',
  sourcemap: false,
  drop: ['console', 'debugger'],
  target: 'node22',
  tsconfig: 'tsconfig.json',
  external: [
    '@eslint-community/eslint-plugin-eslint-comments',
    '@eslint-community/eslint-plugin-eslint-comments/configs',
    '@graphql-eslint/eslint-plugin',
    '@stylistic/eslint-plugin',
    'eslint',
    'eslint/config',
    'eslint-config-prettier',
    'eslint-import-resolver-typescript',
    'eslint-plugin-import-x',
    'eslint-plugin-import-x/meta',
    'eslint-plugin-prettier',
    'eslint-plugin-prettier/recommended',
    'eslint-plugin-vue',
    'globals',
    'typescript',
    'typescript-eslint',
    'vue-eslint-parser',
  ],
})
